# Generated by Django 3.0.5 on 2020-05-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RunID', models.CharField(max_length=100)),
                ('LibraryID', models.CharField(max_length=100)),
                ('SampleID', models.CharField(max_length=100)),
                ('Specie', models.CharField(choices=[('H.sapiens', 'H.sapiens'), ('M.musculus', 'M.musculus'), ('D.melanogaster', 'D.melanogaster')], default='H.sapiens', max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userHome.SeqLibrary')),
            ],
        ),
    ]
