# Generated by Django 3.0.5 on 2020-05-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0004_auto_20200519_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqlibrary',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqData', to='userHome.Project'),
        ),
    ]
