# Generated by Django 3.0.5 on 2020-05-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0005_auto_20200519_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seqlibrary',
            name='Specie',
        ),
        migrations.CreateModel(
            name='GenomeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('specie', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='userHome.Specie')),
            ],
        ),
        migrations.AddField(
            model_name='seqlibrary',
            name='genome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userHome.GenomeVersion'),
        ),
        migrations.AddField(
            model_name='seqlibrary',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userHome.Specie'),
        ),
    ]
