# Generated by Django 3.0.5 on 2020-05-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0006_auto_20200520_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimGaloreParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phred33', models.CharField(max_length=100)),
                ('phred64', models.CharField(max_length=100)),
                ('fastqc', models.CharField(max_length=100)),
                ('fastqc_args', models.CharField(max_length=100)),
                ('adapter', models.CharField(max_length=100)),
                ('adapter2', models.CharField(max_length=100)),
                ('illumina', models.CharField(max_length=100)),
                ('nextera', models.CharField(max_length=100)),
                ('small_rna', models.CharField(max_length=100)),
                ('consider_already_trimmed', models.CharField(max_length=100)),
                ('max_length', models.CharField(max_length=100)),
                ('stringency', models.CharField(max_length=100)),
                ('e', models.CharField(max_length=100)),
                ('gzip', models.CharField(max_length=100)),
                ('dont_gzip', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('max_n', models.CharField(max_length=100)),
                ('trim_n', models.CharField(max_length=100)),
                ('output_dir', models.CharField(max_length=100)),
                ('no_report_file', models.CharField(max_length=100)),
                ('suppress_warn', models.CharField(max_length=100)),
                ('clip_R1', models.CharField(max_length=100)),
                ('clip_R2', models.CharField(max_length=100)),
                ('three_prime_clip_R1', models.CharField(max_length=100)),
                ('three_prime_clip_R2', models.CharField(max_length=100)),
                ('nextseq', models.CharField(max_length=100)),
                ('path_to_cutadapt', models.CharField(max_length=100)),
                ('basename', models.CharField(max_length=100)),
                ('cores', models.CharField(max_length=100)),
                ('hardtrim5', models.CharField(max_length=100)),
                ('hardtrim3', models.CharField(max_length=100)),
                ('clock', models.CharField(max_length=100)),
                ('polyA', models.CharField(max_length=100)),
                ('rrbs', models.CharField(max_length=100)),
                ('non_directional', models.CharField(max_length=100)),
                ('keep', models.CharField(max_length=100)),
                ('paired', models.CharField(max_length=100)),
                ('trim1', models.CharField(max_length=100)),
                ('retain_unpaired', models.CharField(max_length=100)),
                ('length_1', models.CharField(max_length=100)),
                ('length_2', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userHome.Project')),
            ],
        ),
        migrations.CreateModel(
            name='STARParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runThreadN', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userHome.Project')),
            ],
        ),
    ]
