# Generated by Django 3.0.5 on 2020-06-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0007_starparams_trimgaloreparams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STARParams',
        ),
    ]
