# Generated by Django 3.0.5 on 2020-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0009_starparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqlibrary',
            name='BU_ptrn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seqlibrary',
            name='R1len',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
